server:
  port: 8087
  servlet:
    context-path: /notifications
spring:
  application:
    name: notification-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/notification_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:p0stgr3s}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        "[format_sql]": true
        "[show_sql]": false
  jackson:
    serialization:
      fail-on-empty-beans: false
    default-property-inclusion: NON_NULL
  
  # Kafka Configuration - Minimal, inherit từ BaseKafkaConfig
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

---

spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  
  # Kafka Configuration - Minimal, inherit từ BaseKafkaConfig
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: notification-service

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI}/
  instance:
    preferIpAddress: true

logging:
  level:
    "[com.pdh.notification]": DEBUG
    "[org.hibernate.SQL]": INFO
    "[org.springframework.web]": INFO
