--
-- PostgreSQL database dump
--

-- Dumped from database version 17.0
-- Dumped by pg_dump version 17.5

-- Started on 2025-09-15 23:07:13

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 217 (class 1259 OID 57656)
-- Name: databasechangelog; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.databasechangelog (
    id character varying(255) NOT NULL,
    author character varying(255) NOT NULL,
    filename character varying(255) NOT NULL,
    dateexecuted timestamp without time zone NOT NULL,
    orderexecuted integer NOT NULL,
    exectype character varying(10) NOT NULL,
    md5sum character varying(35),
    description character varying(255),
    comments character varying(255),
    tag character varying(255),
    liquibase character varying(20),
    contexts character varying(255),
    labels character varying(255),
    deployment_id character varying(10)
);


ALTER TABLE public.databasechangelog OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 57661)
-- Name: databasechangeloglock; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.databasechangeloglock (
    id integer NOT NULL,
    locked boolean NOT NULL,
    lockgranted timestamp without time zone,
    lockedby character varying(255)
);


ALTER TABLE public.databasechangeloglock OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 57667)
-- Name: media; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.media (
    id bigint NOT NULL,
    created_at timestamp without time zone NOT NULL,
    created_by character varying(255),
    updated_at timestamp without time zone NOT NULL,
    updated_by character varying(255),
    is_deleted boolean NOT NULL,
    deleted_at timestamp without time zone,
    deleted_by character varying(255),
    public_id character varying(255) NOT NULL,
    url character varying(500) NOT NULL,
    secure_url character varying(500) NOT NULL,
    media_type character varying(20) NOT NULL,
    is_active boolean NOT NULL
);


ALTER TABLE public.media OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 57666)
-- Name: media_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.media ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.media_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3414 (class 0 OID 57656)
-- Dependencies: 217
-- Data for Name: databasechangelog; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.databasechangelog (id, author, filename, dateexecuted, orderexecuted, exectype, md5sum, description, comments, tag, liquibase, contexts, labels, deployment_id) FROM stdin;
1757207654533-1	PhamDuyHuy	db/changelog/ddl/001-07-09-changelog.sql	2025-09-08 08:37:51.631834	1	EXECUTED	9:6a919587b3c1ac35c2e3900f2bd37d77	sql		\N	4.31.1	\N	\N	7320665796
1757207654533-2	PhamDuyHuy	db/changelog/ddl/001-07-09-changelog.sql	2025-09-08 08:37:51.716735	2	EXECUTED	9:5aa030fe9dbe3da6d4b830afbd67ef1b	sql		\N	4.31.1	\N	\N	7320665796
1757207654533-3	PhamDuyHuy	db/changelog/ddl/001-07-09-changelog.sql	2025-09-08 08:37:51.751137	3	EXECUTED	9:804160c46dd2fad47b4fed1b58c88446	sql		\N	4.31.1	\N	\N	7320665796
1757207654533-4	PhamDuyHuy	db/changelog/ddl/001-07-09-changelog.sql	2025-09-08 08:37:51.799476	4	EXECUTED	9:2c84e07aa232d1f452de5dccb15ab9d2	sql		\N	4.31.1	\N	\N	7320665796
1757207654533-5	PhamDuyHuy	db/changelog/ddl/001-07-09-changelog.sql	2025-09-08 08:37:51.867744	5	EXECUTED	9:7277766fe687f281888c5bba7d937ef3	sql		\N	4.31.1	\N	\N	7320665796
1757207654533-6	PhamDuyHuy	db/changelog/ddl/001-07-09-changelog.sql	2025-09-08 08:37:51.900609	6	EXECUTED	9:785639a21c93300645a5d7505236bb92	sql		\N	4.31.1	\N	\N	7320665796
1757207654533-7	PhamDuyHuy	db/changelog/ddl/001-07-09-changelog.sql	2025-09-08 08:37:51.924137	7	EXECUTED	9:d26a771cff3cf40690b7ceac99bc7ed8	sql		\N	4.31.1	\N	\N	7320665796
1757207654533-8	PhamDuyHuy	db/changelog/ddl/001-07-09-changelog.sql	2025-09-08 08:37:51.954311	8	EXECUTED	9:459c8aca8f86ffb409b8932a7200ae4d	sql		\N	4.31.1	\N	\N	7320665796
1757360479719-7	PhamDuyHuy	db/changelog/ddl/002-changelog.sql	2025-09-08 23:40:36.937382	9	EXECUTED	9:96e885b19d8df269c9224d1306808c83	sql		\N	4.31.1	\N	\N	7374830585
1757360479719-1	PhamDuyHuy	db/changelog/ddl/002-changelog.sql	2025-09-08 23:40:37.080549	10	EXECUTED	9:284d63fe476a6816910200df6de13cfc	sql		\N	4.31.1	\N	\N	7374830585
1757426207281-2	PhamDuyHuy	db/changelog/ddl/003-changelog.sql	2025-09-09 22:01:53.20994	11	EXECUTED	9:c0014eb8e44d6b583b6467a9494cb56b	sql		\N	4.31.1	\N	\N	7455309700
\.


--
-- TOC entry 3415 (class 0 OID 57661)
-- Dependencies: 218
-- Data for Name: databasechangeloglock; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.databasechangeloglock (id, locked, lockgranted, lockedby) FROM stdin;
1	f	\N	\N
\.


--
-- TOC entry 3417 (class 0 OID 57667)
-- Dependencies: 220
-- Data for Name: media; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.media (id, created_at, created_by, updated_at, updated_by, is_deleted, deleted_at, deleted_by, public_id, url, secure_url, media_type, is_active) FROM stdin;
1	2025-09-09 13:51:29.941817	1c544260-57c6-4e63-ba65-9a529f3783a2	2025-09-09 13:51:29.942249	1c544260-57c6-4e63-ba65-9a529f3783a2	f	\N	\N	hotels/file_lu4dyf	http://res.cloudinary.com/de0ler3wa/image/upload/v1757425888/hotels/file_lu4dyf.png	https://res.cloudinary.com/de0ler3wa/image/upload/v1757425888/hotels/file_lu4dyf.png	image	t
2	2025-09-10 00:23:34.284981	1c544260-57c6-4e63-ba65-9a529f3783a2	2025-09-10 00:23:34.285078	1c544260-57c6-4e63-ba65-9a529f3783a2	f	\N	\N	hotels/file_uubyof	http://res.cloudinary.com/de0ler3wa/image/upload/v1757463812/hotels/file_uubyof.png	https://res.cloudinary.com/de0ler3wa/image/upload/v1757463812/hotels/file_uubyof.png	image	t
3	2025-09-10 01:55:47.281108	1c544260-57c6-4e63-ba65-9a529f3783a2	2025-09-10 01:55:47.281168	1c544260-57c6-4e63-ba65-9a529f3783a2	f	\N	\N	room-types/file_yr53mb	http://res.cloudinary.com/de0ler3wa/image/upload/v1757469346/room-types/file_yr53mb.png	https://res.cloudinary.com/de0ler3wa/image/upload/v1757469346/room-types/file_yr53mb.png	image	t
4	2025-09-10 05:01:08.164483	1c544260-57c6-4e63-ba65-9a529f3783a2	2025-09-10 05:01:08.16455	1c544260-57c6-4e63-ba65-9a529f3783a2	f	\N	\N	rooms/file_whbzic	http://res.cloudinary.com/de0ler3wa/image/upload/v1757480466/rooms/file_whbzic.png	https://res.cloudinary.com/de0ler3wa/image/upload/v1757480466/rooms/file_whbzic.png	image	t
5	2025-09-10 10:38:40.935115	1c544260-57c6-4e63-ba65-9a529f3783a2	2025-09-10 10:38:40.935201	1c544260-57c6-4e63-ba65-9a529f3783a2	f	\N	\N	hotels/file_fpavup	http://res.cloudinary.com/de0ler3wa/image/upload/v1757500718/hotels/file_fpavup.png	https://res.cloudinary.com/de0ler3wa/image/upload/v1757500718/hotels/file_fpavup.png	image	t
6	2025-09-11 23:35:53.912352	1c544260-57c6-4e63-ba65-9a529f3783a2	2025-09-11 23:35:53.912421	1c544260-57c6-4e63-ba65-9a529f3783a2	f	\N	\N	hotels/file_tb6d53	http://res.cloudinary.com/de0ler3wa/image/upload/v1757633752/hotels/file_tb6d53.png	https://res.cloudinary.com/de0ler3wa/image/upload/v1757633752/hotels/file_tb6d53.png	image	t
\.


--
-- TOC entry 3423 (class 0 OID 0)
-- Dependencies: 219
-- Name: media_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.media_id_seq', 6, true);


--
-- TOC entry 3262 (class 2606 OID 57665)
-- Name: databasechangeloglock databasechangeloglock_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.databasechangeloglock
    ADD CONSTRAINT databasechangeloglock_pkey PRIMARY KEY (id);


--
-- TOC entry 3266 (class 2606 OID 57673)
-- Name: media pk_media; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.media
    ADD CONSTRAINT pk_media PRIMARY KEY (id);


--
-- TOC entry 3268 (class 2606 OID 57675)
-- Name: media uc_media_public; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.media
    ADD CONSTRAINT uc_media_public UNIQUE (public_id);


--
-- TOC entry 3263 (class 1259 OID 57676)
-- Name: idx_media_active; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_media_active ON public.media USING btree (is_active);


--
-- TOC entry 3264 (class 1259 OID 57680)
-- Name: idx_media_public_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX idx_media_public_id ON public.media USING btree (public_id);


-- Completed on 2025-09-15 23:07:13

--
-- PostgreSQL database dump complete
--

