version: 3.8
services:
  discovery-service:
    image: phamduyhuyuit/bookingsmart-discovery-service:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    networks:
      - booking-network
    ports:
      - 8761:8761
  booking-service:
    image: phamduyhuyuit/bookingsmart-booking-service:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    networks:
      - booking-network
  flight-service:
    image: phamduyhuyuit/bookingsmart-flight-service:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    networks:
      - booking-network
  hotel-service:
    image: phamduyhuyuit/bookingsmart-hotel-service:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    networks:
      - booking-network
  payment-service:
    image: phamduyhuyuit/bookingsmart-payment-service:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    networks:
      - booking-network
  customer-service:
    image: phamduyhuyuit/bookingsmart-customer-service:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    networks:
      - booking-network
  notification-service:
    image: phamduyhuyuit/bookingsmart-notification-service:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    networks:
      - booking-network
  media-service:
    image: phamduyhuyuit/bookingsmart-media-service:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    networks:
      - booking-network
  transport-service:
    image: phamduyhuyuit/bookingsmart-transport-service:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    networks:
      - booking-network
  storefront-bff:
    image: phamduyhuyuit/bookingsmart-storefront-bff:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    networks:
      - booking-network
    ports:
      - 8080
  backoffice-bff:
    image: phamduyhuyuit/bookingsmart-backoffice-bff:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    networks:
      - booking-network
    ports:
      - 8080
  storefront-fe:
    image: phamduyhuyuit/bookingsmart-storefront-fe:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    networks:
      - booking-network
    ports:
      - 3000
  backoffice-fe:
    image: phamduyhuyuit/bookingsmart-backoffice-fe:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    networks:
      - booking-network
    ports:
      - 3000
networks:
  booking-network:
    driver: overlay
    attachable: True
