server:
  port: 8080

spring:
  application:
    name: BACKOFFICE-BFF

  cloud:
    gateway:
      routes:
        # FLIGHT SERVICE
        - id: flight-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/flight-service/**
          filters:
            - TokenRelay=
            - RewritePath=/api/flight-service/(?<segment>.*), /${segment}
        - id: eureka-web-start
          uri: lb://DISCOVERY-SERVICE
          predicates:
            - Path=/eureka/web
          filters:
            - StripPrefix=2
        - id: eureka-web-other
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**
      default-filters:
        - SaveSession

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    hostname: localhost
    prefer-ip-address: false

logging:
  level:
    root: INFO
    '[com.pdh.gateway]': DEBUG
    '[org.springframework.cloud.gateway]': DEBUG
    '[org.springframework.security]': DEBUG
    '[org.springframework.web.reactive.function.client]': DEBUG
