
server:
  port: 9080
spring:
  profiles:
    active: local
  application:
    name: BACKOFFICE-BFF
logging:
  level:
    "[com.pdh.backoffice]": DEBUG
    "[org.springframework.security]": DEBUG

---
spring:
  config:
    activate:
      on-profile: local
  security:
    oauth2:
      client:
        registration:
          api-client:
            client-id: backoffice-bff
            client-secret: HvSjC1OSQXzDthr9ROecBZaRxA0CHHw6
            scope: profile, email, openid, roles
            provider: keycloak
        provider:
          keycloak:
            issuer-uri: http://localhost:9090/realms/BookingSmart
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: backoffice-bff-group

  cloud:
    gateway:
      routes:
        - id: flight-service
          uri: lb://FLIGHT-SERVICE
          predicates:
            - Path=/api/flights/**
          filters:
            - StripPrefix=1
            - TokenRelay=
        - id: hotel-service
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/api/hotels/**
          filters:
            - StripPrefix=1
            - TokenRelay=
        - id: booking-service
          uri: lb://BOOKING-SERVICE
          predicates:
            - Path=/api/bookings/**, /api/availability/**
          filters:
            - StripPrefix=1
            - TokenRelay=
        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/api/customers/**
          filters:
            - StripPrefix=1
            - TokenRelay=
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/payments/**
          filters:
            - StripPrefix=1
            - TokenRelay=
        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/notifications/**
          filters:
            - StripPrefix=1
            - TokenRelay=
        - id: media-service
          uri: lb://MEDIA-SERVICE
          predicates:
            - Path=/api/media/**
          filters:
            - StripPrefix=1
            - TokenRelay=
        # Administrative routes
        - id: eureka-web-start
          uri: lb://DISCOVERY-SERVICE
          predicates:
            - Path=/eureka/web
          filters:
            - StripPrefix=2
        
        # Default frontend route (lowest priority)
        - id: frontend-fallback
          uri: http://localhost:3000
          predicates:
            - Path=/**
      default-filters:
        - SaveSession
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: false

# Hotel service configuration
hotel:
  service:
    url: http://localhost:8083

---

spring:
  config:
    activate:
      on-profile: docker
  security:
    oauth2:
      client:
        registration:
          api-client:
            client-name: Backoffice
            client-id: backoffice-bff
            client-secret: ${KEYCLOAK_CLIENT_SECRET_BACKOFFICE_BFF}
            scope: profile, email, openid, roles
            provider: keycloak
        provider:
          keycloak:
            issuer-uri: ${JWT_ISSUER_URI}
  cloud:
    gateway:
      routes:
        - id: sse
          uri: ${API_URL}
          predicates:
            - Path=/mcp/**
          filters:
            - RewritePath=/mcp/(?<segment>.*), /$\{segment}
            - TokenRelay=
            - SetResponseHeader=Cache-Control, no-cache, no-transform
            - AddResponseHeader=Connection, keep-alive
        - id: api
          uri: ${API_URL}
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
            - TokenRelay=
        # Default frontend route (lowest priority)
        - id: frontend-fallback
          uri: http://backoffice-fe:3001
          predicates:
            - Path=/**
      default-filters:
        - SaveSession
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: backoffice-bff-group
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI}
  instance:
    prefer-ip-address: true

# Hotel service configuration
hotel:
  service:
    url: http://hotel-service:8080