-- liquibase formatted sql

-- changeset PhamDuyHuy:1751915213284-1
CREATE TABLE airlines
(
    airline_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_by VARCHAR(255),
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_by VARCHAR(255),
    is_deleted BOOLEAN                                 NOT NULL,
    deleted_at TIMESTAMP WITHOUT TIME ZONE,
    deleted_by VARCHAR(255),
    name       VARCHAR(255)                            NOT NULL,
    iata_code  VARCHAR(2),
    logo_url   VARCHAR(500),
    CONSTRAINT pk_airlines PRIMARY KEY (airline_id)
);

-- changeset PhamDuyHuy:1751915213284-2
CREATE TABLE airports
(
    airport_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_by VARCHAR(255),
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_by VARCHAR(255),
    is_deleted BOOLEAN                                 NOT NULL,
    deleted_at TIMESTAMP WITHOUT TIME ZONE,
    deleted_by VARCHAR(255),
    name       VARCHAR(255)                            NOT NULL,
    iata_code  VARCHAR(3)                              NOT NULL,
    city       VARCHAR(100),
    country    VARCHAR(100),
    CONSTRAINT pk_airports PRIMARY KEY (airport_id)
);

-- changeset PhamDuyHuy:1751915213284-3
CREATE TABLE flight_fares
(
    fare_id         UUID           NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_by      VARCHAR(255),
    updated_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_by      VARCHAR(255),
    is_deleted      BOOLEAN        NOT NULL,
    deleted_at      TIMESTAMP WITHOUT TIME ZONE,
    deleted_by      VARCHAR(255),
    schedule_id     UUID           NOT NULL,
    fare_class      VARCHAR(50)    NOT NULL,
    price           DECIMAL(10, 2) NOT NULL,
    available_seats INTEGER        NOT NULL,
    CONSTRAINT pk_flight_fares PRIMARY KEY (fare_id)
);

-- changeset PhamDuyHuy:1751915213284-4
CREATE TABLE flight_inventory
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    flight_leg_id  BIGINT                                  NOT NULL,
    fare_class     VARCHAR(255)                            NOT NULL,
    total_seats    SMALLINT                                NOT NULL,
    reserved_seats SMALLINT                                NOT NULL,
    CONSTRAINT pk_flight_inventory PRIMARY KEY (id)
);

-- changeset PhamDuyHuy:1751915213284-5
CREATE TABLE flight_legs
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    flight_id            BIGINT                                  NOT NULL,
    leg_number           SMALLINT                                NOT NULL,
    departure_airport_id BIGINT                                  NOT NULL,
    arrival_airport_id   BIGINT                                  NOT NULL,
    departure_time       TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    arrival_time         TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_flight_legs PRIMARY KEY (id)
);

-- changeset PhamDuyHuy:1751915213284-6
CREATE TABLE flight_schedules
(
    schedule_id    UUID    NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_by     VARCHAR(255),
    updated_at     TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_by     VARCHAR(255),
    is_deleted     BOOLEAN NOT NULL,
    deleted_at     TIMESTAMP WITHOUT TIME ZONE,
    deleted_by     VARCHAR(255),
    flight_id      BIGINT  NOT NULL,
    departure_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    arrival_time   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    aircraft_type  VARCHAR(100),
    status         VARCHAR(50),
    CONSTRAINT pk_flight_schedules PRIMARY KEY (schedule_id)
);

-- changeset PhamDuyHuy:1751915213284-7
CREATE TABLE flights
(
    flight_id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at            TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_by            VARCHAR(255),
    updated_at            TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_by            VARCHAR(255),
    is_deleted            BOOLEAN                                 NOT NULL,
    deleted_at            TIMESTAMP WITHOUT TIME ZONE,
    deleted_by            VARCHAR(255),
    flight_number         VARCHAR(20)                             NOT NULL,
    airline_id            BIGINT                                  NOT NULL,
    departure_airport_id  BIGINT                                  NOT NULL,
    arrival_airport_id    BIGINT                                  NOT NULL,
    base_duration_minutes INTEGER,
    CONSTRAINT pk_flights PRIMARY KEY (flight_id)
);

-- changeset PhamDuyHuy:1751915213284-8
ALTER TABLE flight_inventory
    ADD CONSTRAINT uc_71fa7a57019dd0aebf1ee54e9 UNIQUE (flight_leg_id, fare_class);

-- changeset PhamDuyHuy:1751915213284-9
ALTER TABLE airlines
    ADD CONSTRAINT uc_airlines_iata_code UNIQUE (iata_code);

-- changeset PhamDuyHuy:1751915213284-10
ALTER TABLE airports
    ADD CONSTRAINT uc_airports_iata_code UNIQUE (iata_code);

-- changeset PhamDuyHuy:1751915213284-11
ALTER TABLE flight_legs
    ADD CONSTRAINT uc_b6b1fbef6a817bc10ec30aeb1 UNIQUE (flight_id, leg_number);

-- changeset PhamDuyHuy:1751915213284-12
ALTER TABLE flights
    ADD CONSTRAINT FK_FLIGHTS_ON_AIRLINE FOREIGN KEY (airline_id) REFERENCES airlines (airline_id);

-- changeset PhamDuyHuy:1751915213284-13
ALTER TABLE flights
    ADD CONSTRAINT FK_FLIGHTS_ON_ARRIVAL_AIRPORT FOREIGN KEY (arrival_airport_id) REFERENCES airports (airport_id);

-- changeset PhamDuyHuy:1751915213284-14
ALTER TABLE flights
    ADD CONSTRAINT FK_FLIGHTS_ON_DEPARTURE_AIRPORT FOREIGN KEY (departure_airport_id) REFERENCES airports (airport_id);

-- changeset PhamDuyHuy:1751915213284-15
ALTER TABLE flight_fares
    ADD CONSTRAINT FK_FLIGHT_FARES_ON_SCHEDULE FOREIGN KEY (schedule_id) REFERENCES flight_schedules (schedule_id);

-- changeset PhamDuyHuy:1751915213284-16
ALTER TABLE flight_inventory
    ADD CONSTRAINT FK_FLIGHT_INVENTORY_ON_FLIGHT_LEG FOREIGN KEY (flight_leg_id) REFERENCES flight_legs (id);

-- changeset PhamDuyHuy:1751915213284-17
ALTER TABLE flight_legs
    ADD CONSTRAINT FK_FLIGHT_LEGS_ON_ARRIVAL_AIRPORT FOREIGN KEY (arrival_airport_id) REFERENCES airports (airport_id);

-- changeset PhamDuyHuy:1751915213284-18
ALTER TABLE flight_legs
    ADD CONSTRAINT FK_FLIGHT_LEGS_ON_DEPARTURE_AIRPORT FOREIGN KEY (departure_airport_id) REFERENCES airports (airport_id);

-- changeset PhamDuyHuy:1751915213284-19
ALTER TABLE flight_legs
    ADD CONSTRAINT FK_FLIGHT_LEGS_ON_FLIGHT FOREIGN KEY (flight_id) REFERENCES flights (flight_id);

-- changeset PhamDuyHuy:1751915213284-20
ALTER TABLE flight_schedules
    ADD CONSTRAINT FK_FLIGHT_SCHEDULES_ON_FLIGHT FOREIGN KEY (flight_id) REFERENCES flights (flight_id);

