server:
  port: 8081

spring:
  profiles:
    active: local
  application:
    name: flight-service
  threads:
    virtual:
      enabled: true
logto:
  audience: https://api.bookingsmart.huypd.me/flight-service
---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/flight_db
    username: postgres
    password: p0stgr3s
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:3001/oidc
          jwk-set-uri: http://localhost:3001/oidc/jwks

  #        opaquetoken:
#          introspection-uri: http://localhost:3001/oidc/token/introspection
#          client-id: ${LOGTO_CLIENT_ID}
#          client-secret: ${LOGTO_CLIENT_SECRET}
  liquibase:
    enabled: true
    default-schema: public
    change-log: classpath:db/changelog/db.changelog-master.yaml
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: false

---

spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: ${LOGTO_ENDPOINT}/oidc/token/introspection
          client-id: ${LOGTO_CLIENT_ID}
          client-secret: ${LOGTO_CLIENT_SECRET}
  liquibase:
    enabled: true
    default-schema: public
    change-log: classpath:db/changelog/db.changelog-master.yaml
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.pdh.flight: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
