-- liquibase formatted sql

-- changeset PhamDuyHuy:1751788371119-1
CREATE TABLE amenities
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(100)                            NOT NULL,
    description   TEXT,
    category      VARCHAR(255),
    icon_url      VARCHAR(255),
    is_active     BOOLEAN,
    display_order INTEGER,
    CONSTRAINT pk_amenities PRIMARY KEY (id)
);

-- changeset PhamDuyHuy:1751788371119-2
CREATE TABLE cities
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    VARCHAR(100)                            NOT NULL,
    country VARCHAR(100)                            NOT NULL,
    CONSTRAINT pk_cities PRIMARY KEY (id)
);

-- changeset PhamDuyHuy:1751788371119-3
CREATE TABLE hotel_amenities
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    hotel_id   BIGINT                                  NOT NULL,
    amenity_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_hotel_amenities PRIMARY KEY (id)
);

-- changeset PhamDuyHuy:1751788371119-4
CREATE TABLE hotel_images
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    hotel_id      BIGINT                                  NOT NULL,
    image_url     VARCHAR(255)                            NOT NULL,
    image_type    VARCHAR(255),
    alt_text      VARCHAR(255),
    display_order INTEGER,
    is_primary    BOOLEAN,
    is_active     BOOLEAN,
    CONSTRAINT pk_hotel_images PRIMARY KEY (id)
);

-- changeset PhamDuyHuy:1751788371119-5
CREATE TABLE hotels
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_on       TIMESTAMP WITHOUT TIME ZONE,
    created_by       VARCHAR(255),
    last_modified_on TIMESTAMP WITHOUT TIME ZONE,
    last_modified_by VARCHAR(255),
    deleted          BOOLEAN                                 NOT NULL,
    is_active        BOOLEAN                                 NOT NULL,
    name             VARCHAR(255)                            NOT NULL,
    address          VARCHAR(255)                            NOT NULL,
    city_id          BIGINT                                  NOT NULL,
    star_rating      SMALLINT,
    description      TEXT,
    latitude         DECIMAL(9, 6),
    longitude        DECIMAL(9, 6),
    checkin_time     time WITHOUT TIME ZONE,
    checkout_time    time WITHOUT TIME ZONE,
    CONSTRAINT pk_hotels PRIMARY KEY (id)
);

-- changeset PhamDuyHuy:1751788371119-6
CREATE TABLE reviews
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_on       TIMESTAMP WITHOUT TIME ZONE,
    created_by       VARCHAR(255),
    last_modified_on TIMESTAMP WITHOUT TIME ZONE,
    last_modified_by VARCHAR(255),
    deleted          BOOLEAN                                 NOT NULL,
    is_active        BOOLEAN                                 NOT NULL,
    hotel_id         BIGINT                                  NOT NULL,
    user_id          UUID,
    rating           SMALLINT                                NOT NULL,
    comment_text     TEXT,
    CONSTRAINT pk_reviews PRIMARY KEY (id)
);

-- changeset PhamDuyHuy:1751788371119-7
CREATE TABLE room_amenities
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_on       TIMESTAMP WITHOUT TIME ZONE,
    created_by       VARCHAR(255),
    last_modified_on TIMESTAMP WITHOUT TIME ZONE,
    last_modified_by VARCHAR(255),
    deleted          BOOLEAN                                 NOT NULL,
    is_active        BOOLEAN                                 NOT NULL,
    room_id          BIGINT                                  NOT NULL,
    amenity_id       BIGINT                                  NOT NULL,
    display_order    INTEGER,
    CONSTRAINT pk_room_amenities PRIMARY KEY (id)
);

-- changeset PhamDuyHuy:1751788371119-8
CREATE TABLE room_availability
(
    availability_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    room_type_id    BIGINT                                  NOT NULL,
    date            date                                    NOT NULL,
    total_inventory SMALLINT                                NOT NULL,
    total_reserved  SMALLINT                                NOT NULL,
    price_override  DECIMAL(12, 2),
    CONSTRAINT pk_room_availability PRIMARY KEY (availability_id)
);

-- changeset PhamDuyHuy:1751788371119-9
CREATE TABLE room_images
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_on       TIMESTAMP WITHOUT TIME ZONE,
    created_by       VARCHAR(255),
    last_modified_on TIMESTAMP WITHOUT TIME ZONE,
    last_modified_by VARCHAR(255),
    deleted          BOOLEAN                                 NOT NULL,
    is_active        BOOLEAN                                 NOT NULL,
    room_id          BIGINT                                  NOT NULL,
    image_url        VARCHAR(255)                            NOT NULL,
    image_type       VARCHAR(255),
    alt_text         VARCHAR(255),
    display_order    INTEGER,
    is_primary       BOOLEAN,
    CONSTRAINT pk_room_images PRIMARY KEY (id)
);

-- changeset PhamDuyHuy:1751788371119-10
CREATE TABLE rooms
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_on       TIMESTAMP WITHOUT TIME ZONE,
    created_by       VARCHAR(255),
    last_modified_on TIMESTAMP WITHOUT TIME ZONE,
    last_modified_by VARCHAR(255),
    deleted          BOOLEAN                                 NOT NULL,
    is_active        BOOLEAN                                 NOT NULL,
    hotel_id         BIGINT                                  NOT NULL,
    room_number      VARCHAR(255)                            NOT NULL,
    room_type        VARCHAR(255)                            NOT NULL,
    description      VARCHAR(255),
    price            DECIMAL(10, 2)                          NOT NULL,
    max_occupancy    INTEGER,
    bed_type         VARCHAR(255),
    room_size        INTEGER,
    is_available     BOOLEAN,
    CONSTRAINT pk_rooms PRIMARY KEY (id)
);

-- changeset PhamDuyHuy:1751788371119-11
CREATE TABLE roomtypes
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_on        TIMESTAMP WITHOUT TIME ZONE,
    created_by        VARCHAR(255),
    last_modified_on  TIMESTAMP WITHOUT TIME ZONE,
    last_modified_by  VARCHAR(255),
    deleted           BOOLEAN                                 NOT NULL,
    is_active         BOOLEAN                                 NOT NULL,
    hotel_id          BIGINT                                  NOT NULL,
    name              VARCHAR(100)                            NOT NULL,
    description       TEXT,
    capacity_adults   SMALLINT                                NOT NULL,
    capacity_children SMALLINT                                NOT NULL,
    base_price        DECIMAL(12, 2)                          NOT NULL,
    CONSTRAINT pk_roomtypes PRIMARY KEY (id)
);

-- changeset PhamDuyHuy:1751788371119-12
ALTER TABLE amenities
    ADD CONSTRAINT uc_amenities_name UNIQUE (name);

-- changeset PhamDuyHuy:1751788371119-13
ALTER TABLE hotels
    ADD CONSTRAINT FK_HOTELS_ON_CITY FOREIGN KEY (city_id) REFERENCES cities (id);

-- changeset PhamDuyHuy:1751788371119-14
ALTER TABLE hotel_amenities
    ADD CONSTRAINT FK_HOTEL_AMENITIES_ON_AMENITY FOREIGN KEY (amenity_id) REFERENCES amenities (id);

-- changeset PhamDuyHuy:1751788371119-15
ALTER TABLE hotel_amenities
    ADD CONSTRAINT FK_HOTEL_AMENITIES_ON_HOTEL FOREIGN KEY (hotel_id) REFERENCES hotels (id);

-- changeset PhamDuyHuy:1751788371119-16
ALTER TABLE hotel_images
    ADD CONSTRAINT FK_HOTEL_IMAGES_ON_HOTEL FOREIGN KEY (hotel_id) REFERENCES hotels (id);

-- changeset PhamDuyHuy:1751788371119-17
ALTER TABLE reviews
    ADD CONSTRAINT FK_REVIEWS_ON_HOTEL FOREIGN KEY (hotel_id) REFERENCES hotels (id);

-- changeset PhamDuyHuy:1751788371119-18
ALTER TABLE rooms
    ADD CONSTRAINT FK_ROOMS_ON_HOTEL FOREIGN KEY (hotel_id) REFERENCES hotels (id);

-- changeset PhamDuyHuy:1751788371119-19
ALTER TABLE roomtypes
    ADD CONSTRAINT FK_ROOMTYPES_ON_HOTEL FOREIGN KEY (hotel_id) REFERENCES hotels (id);

-- changeset PhamDuyHuy:1751788371119-20
ALTER TABLE room_amenities
    ADD CONSTRAINT FK_ROOM_AMENITIES_ON_AMENITY FOREIGN KEY (amenity_id) REFERENCES amenities (id);

-- changeset PhamDuyHuy:1751788371119-21
ALTER TABLE room_amenities
    ADD CONSTRAINT FK_ROOM_AMENITIES_ON_ROOM FOREIGN KEY (room_id) REFERENCES rooms (id);

-- changeset PhamDuyHuy:1751788371119-22
ALTER TABLE room_availability
    ADD CONSTRAINT FK_ROOM_AVAILABILITY_ON_ROOM_TYPE FOREIGN KEY (room_type_id) REFERENCES roomtypes (id);

-- changeset PhamDuyHuy:1751788371119-23
ALTER TABLE room_images
    ADD CONSTRAINT FK_ROOM_IMAGES_ON_ROOM FOREIGN KEY (room_id) REFERENCES rooms (id);

