-- liquibase formatted sql

-- changeset PhamDuyHuy:1751915157999-1
CREATE TABLE amenities
(
    amenity_id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_by    VARCHAR(255),
    updated_at    TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_by    VARCHAR(255),
    is_deleted    BOOLEAN                                 NOT NULL,
    deleted_at    TIMESTAMP WITHOUT TIME ZONE,
    deleted_by    VARCHAR(255),
    name          VARCHAR(100)                            NOT NULL,
    icon_url      VARCHAR(255),
    is_active     BOOLEAN,
    display_order INTEGER,
    CONSTRAINT pk_amenities PRIMARY KEY (amenity_id)
);

-- changeset PhamDuyHuy:1751915157999-2
CREATE TABLE cities
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    VARCHAR(100)                            NOT NULL,
    country VARCHAR(100)                            NOT NULL,
    CONSTRAINT pk_cities PRIMARY KEY (id)
);

-- changeset PhamDuyHuy:1751915157999-3
CREATE TABLE hotel_amenities
(
    hotel_id   BIGINT NOT NULL,
    amenity_id BIGINT NOT NULL,
    CONSTRAINT pk_hotel_amenities PRIMARY KEY (hotel_id, amenity_id)
);

-- changeset PhamDuyHuy:1751915157999-4
CREATE TABLE hotel_images
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    hotel_id      BIGINT                                  NOT NULL,
    image_url     VARCHAR(255)                            NOT NULL,
    image_type    VARCHAR(255),
    alt_text      VARCHAR(255),
    display_order INTEGER,
    is_primary    BOOLEAN,
    is_active     BOOLEAN,
    CONSTRAINT pk_hotel_images PRIMARY KEY (id)
);

-- changeset PhamDuyHuy:1751915157999-5
CREATE TABLE hotels
(
    hotel_id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_by  VARCHAR(255),
    updated_at  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_by  VARCHAR(255),
    is_deleted  BOOLEAN                                 NOT NULL,
    deleted_at  TIMESTAMP WITHOUT TIME ZONE,
    deleted_by  VARCHAR(255),
    name        VARCHAR(255)                            NOT NULL,
    address     VARCHAR(500),
    city        VARCHAR(100),
    country     VARCHAR(100),
    star_rating DECIMAL(2, 1),
    description TEXT,
    latitude    DECIMAL(9, 6),
    longitude   DECIMAL(9, 6),
    CONSTRAINT pk_hotels PRIMARY KEY (hotel_id)
);

-- changeset PhamDuyHuy:1751915157999-6
CREATE TABLE reviews
(
    review_id    UUID    NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_by   VARCHAR(255),
    updated_at   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_by   VARCHAR(255),
    is_deleted   BOOLEAN NOT NULL,
    deleted_at   TIMESTAMP WITHOUT TIME ZONE,
    deleted_by   VARCHAR(255),
    hotel_id     BIGINT  NOT NULL,
    user_id      UUID    NOT NULL,
    rating       INTEGER NOT NULL,
    comment_text TEXT,
    CONSTRAINT pk_reviews PRIMARY KEY (review_id)
);

-- changeset PhamDuyHuy:1751915157999-7
CREATE TABLE room_amenities
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_by    VARCHAR(255),
    updated_at    TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_by    VARCHAR(255),
    is_deleted    BOOLEAN                                 NOT NULL,
    deleted_at    TIMESTAMP WITHOUT TIME ZONE,
    deleted_by    VARCHAR(255),
    room_id       BIGINT                                  NOT NULL,
    amenity_id    BIGINT                                  NOT NULL,
    is_active     BOOLEAN,
    display_order INTEGER,
    CONSTRAINT pk_room_amenities PRIMARY KEY (id)
);

-- changeset PhamDuyHuy:1751915157999-8
CREATE TABLE room_availability
(
    availability_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_by      VARCHAR(255),
    updated_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_by      VARCHAR(255),
    is_deleted      BOOLEAN                                 NOT NULL,
    deleted_at      TIMESTAMP WITHOUT TIME ZONE,
    deleted_by      VARCHAR(255),
    room_type_id    BIGINT                                  NOT NULL,
    date            date                                    NOT NULL,
    total_inventory INTEGER                                 NOT NULL,
    total_reserved  INTEGER                                 NOT NULL,
    CONSTRAINT pk_room_availability PRIMARY KEY (availability_id)
);

-- changeset PhamDuyHuy:1751915157999-9
CREATE TABLE room_images
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_by    VARCHAR(255),
    updated_at    TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_by    VARCHAR(255),
    is_deleted    BOOLEAN                                 NOT NULL,
    deleted_at    TIMESTAMP WITHOUT TIME ZONE,
    deleted_by    VARCHAR(255),
    room_id       BIGINT                                  NOT NULL,
    image_url     VARCHAR(255)                            NOT NULL,
    image_type    VARCHAR(255),
    alt_text      VARCHAR(255),
    display_order INTEGER,
    is_primary    BOOLEAN,
    is_active     BOOLEAN,
    CONSTRAINT pk_room_images PRIMARY KEY (id)
);

-- changeset PhamDuyHuy:1751915157999-10
CREATE TABLE room_types
(
    room_type_id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_by      VARCHAR(255),
    updated_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_by      VARCHAR(255),
    is_deleted      BOOLEAN                                 NOT NULL,
    deleted_at      TIMESTAMP WITHOUT TIME ZONE,
    deleted_by      VARCHAR(255),
    hotel_id        BIGINT                                  NOT NULL,
    name            VARCHAR(255)                            NOT NULL,
    description     TEXT,
    capacity_adults INTEGER,
    base_price      DECIMAL(10, 2),
    CONSTRAINT pk_room_types PRIMARY KEY (room_type_id)
);

-- changeset PhamDuyHuy:1751915157999-11
CREATE TABLE rooms
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_by    VARCHAR(255),
    updated_at    TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_by    VARCHAR(255),
    is_deleted    BOOLEAN                                 NOT NULL,
    deleted_at    TIMESTAMP WITHOUT TIME ZONE,
    deleted_by    VARCHAR(255),
    hotel_id      BIGINT                                  NOT NULL,
    room_number   VARCHAR(255)                            NOT NULL,
    room_type     VARCHAR(255)                            NOT NULL,
    description   VARCHAR(255),
    price         DECIMAL(10, 2)                          NOT NULL,
    max_occupancy INTEGER,
    bed_type      VARCHAR(255),
    room_size     INTEGER,
    is_available  BOOLEAN,
    CONSTRAINT pk_rooms PRIMARY KEY (id)
);

-- changeset PhamDuyHuy:1751915157999-12
ALTER TABLE room_availability
    ADD CONSTRAINT uc_112ec41f887b3e8c2ac96d482 UNIQUE (room_type_id, date);

-- changeset PhamDuyHuy:1751915157999-13
ALTER TABLE amenities
    ADD CONSTRAINT uc_amenities_name UNIQUE (name);

-- changeset PhamDuyHuy:1751915157999-14
ALTER TABLE hotel_amenities
    ADD CONSTRAINT FK_HOTEL_AMENITIES_ON_AMENITY FOREIGN KEY (amenity_id) REFERENCES amenities (amenity_id);

-- changeset PhamDuyHuy:1751915157999-15
ALTER TABLE hotel_amenities
    ADD CONSTRAINT FK_HOTEL_AMENITIES_ON_HOTEL FOREIGN KEY (hotel_id) REFERENCES hotels (hotel_id);

-- changeset PhamDuyHuy:1751915157999-16
ALTER TABLE hotel_images
    ADD CONSTRAINT FK_HOTEL_IMAGES_ON_HOTEL FOREIGN KEY (hotel_id) REFERENCES hotels (hotel_id);

-- changeset PhamDuyHuy:1751915157999-17
ALTER TABLE reviews
    ADD CONSTRAINT FK_REVIEWS_ON_HOTEL FOREIGN KEY (hotel_id) REFERENCES hotels (hotel_id);

-- changeset PhamDuyHuy:1751915157999-18
ALTER TABLE rooms
    ADD CONSTRAINT FK_ROOMS_ON_HOTEL FOREIGN KEY (hotel_id) REFERENCES hotels (hotel_id);

-- changeset PhamDuyHuy:1751915157999-19
ALTER TABLE room_amenities
    ADD CONSTRAINT FK_ROOM_AMENITIES_ON_AMENITY FOREIGN KEY (amenity_id) REFERENCES amenities (amenity_id);

-- changeset PhamDuyHuy:1751915157999-20
ALTER TABLE room_amenities
    ADD CONSTRAINT FK_ROOM_AMENITIES_ON_ROOM FOREIGN KEY (room_id) REFERENCES rooms (id);

-- changeset PhamDuyHuy:1751915157999-21
ALTER TABLE room_availability
    ADD CONSTRAINT FK_ROOM_AVAILABILITY_ON_ROOM_TYPE FOREIGN KEY (room_type_id) REFERENCES room_types (room_type_id);

-- changeset PhamDuyHuy:1751915157999-22
ALTER TABLE room_images
    ADD CONSTRAINT FK_ROOM_IMAGES_ON_ROOM FOREIGN KEY (room_id) REFERENCES rooms (id);

-- changeset PhamDuyHuy:1751915157999-23
ALTER TABLE room_types
    ADD CONSTRAINT FK_ROOM_TYPES_ON_HOTEL FOREIGN KEY (hotel_id) REFERENCES hotels (hotel_id);

