-- liquibase formatted sql

-- changeset PhamDuyHuy:1757320810881-1
CREATE TABLE hotel_images
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    media_id BIGINT,
    hotel_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_hotel_images PRIMARY KEY (id)
);

-- changeset PhamDuyHuy:1757320810881-2
CREATE TABLE room_images
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    media_id BIGINT,
    room_id  BIGINT                                  NOT NULL,
    CONSTRAINT pk_room_images PRIMARY KEY (id)
);

-- changeset PhamDuyHuy:1757320810881-3
CREATE TABLE room_type_images
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    media_id     BIGINT,
    room_type_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_room_type_images PRIMARY KEY (id)
);

-- changeset PhamDuyHuy:1757320810881-4
ALTER TABLE hotel_images
    ADD CONSTRAINT FK_HOTEL_IMAGES_ON_HOTEL FOREIGN KEY (hotel_id) REFERENCES hotels (hotel_id);

-- changeset PhamDuyHuy:1757320810881-5
ALTER TABLE room_images
    ADD CONSTRAINT FK_ROOM_IMAGES_ON_ROOM FOREIGN KEY (room_id) REFERENCES rooms (id);

-- changeset PhamDuyHuy:1757320810881-6
ALTER TABLE room_type_images
    ADD CONSTRAINT FK_ROOM_TYPE_IMAGES_ON_ROOM_TYPE FOREIGN KEY (room_type_id) REFERENCES room_types (room_type_id);

