server:
  port: 8036
  servlet:
    context-path: /ai
  # Tomcat configuration for large payloads
  tomcat:
    max-http-form-post-size: 10MB
    max-swallow-size: 10MB

# OpenAPI Documentation Configuration
#springdoc:
#  api-docs:
#    path: /api/docs
#    enabled: true
#  swagger-ui:
#    path: /api/swagger-ui
#    enabled: true
#    operationsSorter: method
#    tagsSorter: alpha
#    try-it-out-enabled: true
#  show-actuator: true

spring:
  profiles:
    active: local
  application:
    name: aiAgent-service
  threads:
    virtual:
      enabled: true
  # Servlet multipart configuration for large file uploads
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
  autoconfigure:
    exclude:
      - org.springframework.ai.mcp.client.autoconfigure.SseWebFluxTransportAutoConfiguration
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.format_sql: true
      hibernate.jdbc.lob.non_contextual_creation: true
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  ai:
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: never
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/ai_db
    username: postgres
    password: p0stgr3s
    driver-class-name: org.postgresql.Driver
  ai:
    ollama:
      init:
        pull-model-strategy: when_missing
        embedding:
          include: false
      chat:
        options:
          model: qwen3:4b
          temperature: 0.0
    mistralai:
      api-key: ${MISTRAL_API_KEY}
      chat:
        options:
          model: voxtral-mini-latest 

            
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: never

    mcp:
      client:
        enabled: true
        name: bookingsmrt-mcp-client
        version: 1.0.0

        request-timeout: 300s
        type: async
        root-change-notification: true
        toolcallback.enabled: true
        sse:
          connections:
            server1:
              url: http://localhost:8082
              sse-endpoint: /hotels/sse
            server2:
              url: http://localhost:8081
              sse-endpoint: /flights/sse
        stdio:
          connections:
            openweather:
              command: docker
              args:
                - run
                - -i
                - --rm
                - -e
                - OWM_API_KEY
                - mcp/openweather
              env:
                OWM_API_KEY: ${OWM_API_KEY}
            mapbox:
              command: docker
              args:
                - run
                - -i
                - --rm
                - -e
                - MAPBOX_ACCESS_TOKEN
                - mcp/mapbox
              env:
                MAPBOX_ACCESS_TOKEN: ${MAPBOX_ACCESS_TOKEN}
        initialized: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/BookingSmart
      client:
        registration:
          my-client1:
            provider: auth-server
            client-id: ai-agent
            client-secret: ${BOOKING_SMART_AI_CLIENT_SECRET}
            authorization-grant-type: client_credentials
            scope:
              - mcp
        provider:
          auth-server:
            token-uri: http://localhost:9090/realms/BookingSmart/protocol/openid-connect/token
---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI}
      client:
        registration:
          my-client1:
            provider: auth-server
            client-id: ai-agent
            client-secret: ${BOOKING_SMART_AI_CLIENT_SECRET}
            authorization-grant-type: client_credentials
            scope:
              - mcp
        provider:
          auth-server:
            token-uri: ${KEYCLOAK_HOST}/realms/BookingSmart/protocol/openid-connect/token

  ai:
    openai:
      api-key: ${GEMINI_API_KEY}
      base-url: https://generativelanguage.googleapis.com/v1beta/openai/
      chat:
        options:
          model: gemini-2.5-flash
          temperature: 0.3
#    ollama:
#      init:
#
#        pull-model-strategy: when_missing
#        embedding:
#          include: false
#      chat:
#        options:
#          model: qwen3:4b
#          temperature: 0.0
#      base-url: http://ollama:11434
    mistralai:
      api-key: ${MISTRAL_API_KEY}
      chat:
        options:
          model: voxtral-small-2507
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: never

    mcp:
      client:
        enabled: true
        name: bookingsmart-mcp-client
        version: 1.0.0
        type: sync
        request-timeout: 300s

        root-change-notification: true
        toolcallback.enabled: true
        sse:
          connections:
            hotel-mcp-server:
              url: http://hotel-service
              sse-endpoint: /hotels/sse
            flight-mcp-server:
              url: http://flight-service
              sse-endpoint: /flights/sse
        stdio:
          
          connections:
            openweather:
              command: docker
              args:
                - run
                - -i
                - --rm
                - -e
                - OWM_API_KEY
                - mcp/openweather
              env:
                OWM_API_KEY: ${OWM_API_KEY}
            mapbox:
              command: docker
              args:
                - run
                - -i
                - --rm
                - -e
                - MAPBOX_ACCESS_TOKEN
                - mcp/mapbox
              env:
                MAPBOX_ACCESS_TOKEN: ${MAPBOX_ACCESS_TOKEN}
        initialized: true

# Logging Configuration for Tool Tracking
# logging:
#   level:
#     '[com.pdh.ai.agent.CoreAgent]': INFO
#     '[com.pdh.ai.service.ToolResultCollector]': INFO
#     '[com.pdh.ai.agent.mcp.client.CustomSyncMcpToolCallbackProvider]': INFO
#     '[com.pdh.ai.agent.advisor.LoggingAdvisor]': INFO
#     '[org.springframework.ai.mcp]': DEBUG
#     '[org.springframework.ai.tool]': DEBUG
#     '[io.modelcontextprotocol]': DEBUG
#   pattern:
#     console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
#     file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI}
  instance:
    prefer-ip-address: true
