# OpenAPI Documentation Configuration
springdoc:
  api-docs:
    path: /api/docs
    enabled: true
  swagger-ui:
    path: /api/swagger-ui
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
    try-it-out-enabled: true
    oauth:
      clientId: ${keycloak.client-id:bookingsmart-api}
      realm: ${keycloak.realm:bookingsmart}
      appName: ${spring.application.name}
  show-actuator: true
  group-configs:
    - group: 'public'
      display-name: 'Public API'
      paths-to-match: '/storefront/**'
    - group: 'admin'
      display-name: 'Admin API'
      paths-to-match: '/backoffice/**'
    - group: 'partner'
      display-name: 'Partner API'
      paths-to-match: '/backoffice/partner/**'
    - group: 'monitoring'
      display-name: 'Monitoring & Health'
      paths-to-match: '**/health'

# API Documentation Properties
api:
  info:
    title: Customer Service API
    description: Customer management and profile API for the BookingSmart platform
    version: '@project.version@'
    contact:
      name: BookingSmart Customer Team
      email: customer-team@bookingsmart.com
    license:
      name: MIT License
      url: https://opensource.org/licenses/MIT
    oauth2:
      authorization-url: http://localhost:8080/realms/bookingsmart/protocol/openid-connect/auth
      token-url: http://localhost:8080/realms/bookingsmart/protocol/openid-connect/token
      refresh-url: http://localhost:8080/realms/bookingsmart/protocol/openid-connect/token
      scopes:
        admin: Administrative access to customer management
        customer: Customer access to profile operations
        partner: Partner access to customer integration endpoints