-- liquibase formatted sql

-- changeset PhamDuyHuy:1751995700423-1
CREATE TABLE outbox_events
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_by     VARCHAR(255),
    updated_at     TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_by     VARCHAR(255),
    is_deleted     BOOLEAN                                 NOT NULL,
    deleted_at     TIMESTAMP WITHOUT TIME ZONE,
    deleted_by     VARCHAR(255),
    event_id       VARCHAR(255)                            NOT NULL,
    event_type     VARCHAR(255)                            NOT NULL,
    aggregate_id   VARCHAR(255)                            NOT NULL,
    aggregate_type VARCHAR(255)                            NOT NULL,
    payload        TEXT                                    NOT NULL,
    processed      BOOLEAN                                 NOT NULL,
    processed_at   TIMESTAMP WITHOUT TIME ZONE,
    retry_count    INTEGER                                 NOT NULL,
    max_retries    INTEGER                                 NOT NULL,
    next_retry_at  TIMESTAMP WITHOUT TIME ZONE,
    error_message  TEXT,
    CONSTRAINT pk_outbox_events PRIMARY KEY (id)
);

-- changeset PhamDuyHuy:1751995700423-2
CREATE TABLE payment_methods
(
    method_id              UUID         NOT NULL,
    created_at             TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_by             VARCHAR(255),
    updated_at             TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_by             VARCHAR(255),
    is_deleted             BOOLEAN      NOT NULL,
    deleted_at             TIMESTAMP WITHOUT TIME ZONE,
    deleted_by             VARCHAR(255),
    user_id                UUID         NOT NULL,
    method_type            VARCHAR(255) NOT NULL,
    provider               VARCHAR(255) NOT NULL,
    display_name           VARCHAR(100) NOT NULL,
    card_last_four         VARCHAR(4),
    card_brand             VARCHAR(20),
    card_expiry_month      INTEGER,
    card_expiry_year       INTEGER,
    card_holder_name       VARCHAR(100),
    wallet_id              VARCHAR(100),
    wallet_email           VARCHAR(100),
    bank_name              VARCHAR(100),
    bank_account_last_four VARCHAR(4),
    provider_data          TEXT,
    is_verified            BOOLEAN      NOT NULL,
    is_default             BOOLEAN      NOT NULL,
    is_active              BOOLEAN      NOT NULL,
    token                  VARCHAR(500),
    fingerprint            VARCHAR(100),
    country_code           VARCHAR(2),
    currency               VARCHAR(3),
    notes                  TEXT,
    CONSTRAINT pk_payment_methods PRIMARY KEY (method_id)
);

-- changeset PhamDuyHuy:1751995700423-3
CREATE TABLE payment_outbox_events
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_by     VARCHAR(255),
    updated_at     TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_by     VARCHAR(255),
    is_deleted     BOOLEAN                                 NOT NULL,
    deleted_at     TIMESTAMP WITHOUT TIME ZONE,
    deleted_by     VARCHAR(255),
    event_id       VARCHAR(255)                            NOT NULL,
    event_type     VARCHAR(100)                            NOT NULL,
    aggregate_id   VARCHAR(255)                            NOT NULL,
    aggregate_type VARCHAR(50)                             NOT NULL,
    saga_id        VARCHAR(255),
    booking_id     UUID,
    user_id        UUID,
    payload        TEXT                                    NOT NULL,
    headers        TEXT,
    processed      BOOLEAN                                 NOT NULL,
    processed_at   TIMESTAMP WITHOUT TIME ZONE,
    retry_count    INTEGER                                 NOT NULL,
    max_retries    INTEGER                                 NOT NULL,
    next_retry_at  TIMESTAMP WITHOUT TIME ZONE,
    last_error     TEXT,
    topic          VARCHAR(100),
    partition_key  VARCHAR(100),
    priority       INTEGER                                 NOT NULL,
    expires_at     TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_payment_outbox_events PRIMARY KEY (id)
);

-- changeset PhamDuyHuy:1751995700423-4
CREATE TABLE payment_saga_logs
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at             TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_by             VARCHAR(255),
    updated_at             TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_by             VARCHAR(255),
    is_deleted             BOOLEAN                                 NOT NULL,
    deleted_at             TIMESTAMP WITHOUT TIME ZONE,
    deleted_by             VARCHAR(255),
    payment_id             UUID                                    NOT NULL,
    saga_id                VARCHAR(255)                            NOT NULL,
    transaction_id         UUID,
    step_name              VARCHAR(100)                            NOT NULL,
    step_type              VARCHAR(50)                             NOT NULL,
    from_status            VARCHAR(255),
    to_status              VARCHAR(255)                            NOT NULL,
    event_type             VARCHAR(100)                            NOT NULL,
    event_payload          TEXT,
    compensation_data      TEXT,
    is_compensation        BOOLEAN                                 NOT NULL,
    is_successful          BOOLEAN                                 NOT NULL,
    error_message          TEXT,
    error_code             VARCHAR(50),
    retry_count            INTEGER                                 NOT NULL,
    execution_time_ms      BIGINT,
    processed_at           TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    gateway_response       TEXT,
    gateway_transaction_id VARCHAR(100),
    booking_id             UUID,
    user_id                UUID,
    metadata               TEXT,
    CONSTRAINT pk_payment_saga_logs PRIMARY KEY (id)
);

-- changeset PhamDuyHuy:1751995700423-5
CREATE TABLE payment_transactions
(
    transaction_id          UUID           NOT NULL,
    created_at              TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_by              VARCHAR(255),
    updated_at              TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_by              VARCHAR(255),
    is_deleted              BOOLEAN        NOT NULL,
    deleted_at              TIMESTAMP WITHOUT TIME ZONE,
    deleted_by              VARCHAR(255),
    payment_id              UUID           NOT NULL,
    transaction_reference   VARCHAR(50)    NOT NULL,
    transaction_type        VARCHAR(255)   NOT NULL,
    status                  VARCHAR(255)   NOT NULL,
    amount                  DECIMAL(12, 2) NOT NULL,
    currency                VARCHAR(3)     NOT NULL,
    description             TEXT,
    provider                VARCHAR(255)   NOT NULL,
    gateway_transaction_id  VARCHAR(100),
    gateway_reference       VARCHAR(100),
    gateway_response        TEXT,
    gateway_status          VARCHAR(50),
    gateway_fee             DECIMAL(12, 2),
    initiated_at            TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    processed_at            TIMESTAMP WITHOUT TIME ZONE,
    completed_at            TIMESTAMP WITHOUT TIME ZONE,
    expired_at              TIMESTAMP WITHOUT TIME ZONE,
    parent_transaction_id   UUID,
    original_transaction_id UUID,
    failure_reason          TEXT,
    failure_code            VARCHAR(50),
    retry_count             INTEGER        NOT NULL,
    max_retries             INTEGER        NOT NULL,
    saga_id                 VARCHAR(255),
    saga_step               VARCHAR(50),
    is_compensation         BOOLEAN        NOT NULL,
    ip_address              VARCHAR(45),
    user_agent              TEXT,
    metadata                TEXT,
    notes                   TEXT,
    CONSTRAINT pk_payment_transactions PRIMARY KEY (transaction_id)
);

-- changeset PhamDuyHuy:1751995700423-6
CREATE TABLE payments
(
    payment_id             UUID           NOT NULL,
    created_at             TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_by             VARCHAR(255),
    updated_at             TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_by             VARCHAR(255),
    is_deleted             BOOLEAN        NOT NULL,
    deleted_at             TIMESTAMP WITHOUT TIME ZONE,
    deleted_by             VARCHAR(255),
    payment_reference      VARCHAR(50)    NOT NULL,
    booking_id             UUID           NOT NULL,
    user_id                UUID           NOT NULL,
    customer_id            UUID,
    saga_id                VARCHAR(255)   NOT NULL,
    saga_step              VARCHAR(50),
    amount                 DECIMAL(12, 2) NOT NULL,
    currency               VARCHAR(3)     NOT NULL,
    description            TEXT,
    status                 VARCHAR(255)   NOT NULL,
    method_type            VARCHAR(255)   NOT NULL,
    provider               VARCHAR(255)   NOT NULL,
    payment_method_id      UUID,
    gateway_transaction_id VARCHAR(100),
    gateway_response       TEXT,
    gateway_status         VARCHAR(50),
    initiated_at           TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    processed_at           TIMESTAMP WITHOUT TIME ZONE,
    confirmed_at           TIMESTAMP WITHOUT TIME ZONE,
    expired_at             TIMESTAMP WITHOUT TIME ZONE,
    failure_reason         TEXT,
    retry_count            INTEGER        NOT NULL,
    max_retries            INTEGER        NOT NULL,
    refunded_amount        DECIMAL(12, 2),
    is_refundable          BOOLEAN        NOT NULL,
    refund_deadline        TIMESTAMP WITHOUT TIME ZONE,
    ip_address             VARCHAR(45),
    user_agent             TEXT,
    risk_score             INTEGER,
    is_flagged             BOOLEAN        NOT NULL,
    metadata               TEXT,
    notes                  TEXT,
    CONSTRAINT pk_payments PRIMARY KEY (payment_id)
);

-- changeset PhamDuyHuy:1751995700423-7
ALTER TABLE outbox_events
    ADD CONSTRAINT uc_outbox_events_event UNIQUE (event_id);

-- changeset PhamDuyHuy:1751995700423-8
ALTER TABLE payment_outbox_events
    ADD CONSTRAINT uc_payment_outbox_events_event UNIQUE (event_id);

-- changeset PhamDuyHuy:1751995700423-9
ALTER TABLE payments
    ADD CONSTRAINT uc_payments_payment_reference UNIQUE (payment_reference);

-- changeset PhamDuyHuy:1751995700423-10
ALTER TABLE payment_saga_logs
    ADD CONSTRAINT FK_PAYMENT_SAGA_LOGS_ON_PAYMENT FOREIGN KEY (payment_id) REFERENCES payments (payment_id);

-- changeset PhamDuyHuy:1751995700423-11
ALTER TABLE payment_transactions
    ADD CONSTRAINT FK_PAYMENT_TRANSACTIONS_ON_PAYMENT FOREIGN KEY (payment_id) REFERENCES payments (payment_id);

