-- liquibase formatted sql

-- changeset PhamDuyHuy:1751994419139-2
CREATE TABLE outbox
(
    id             UUID         NOT NULL,
    aggregate_type VARCHAR(255) NOT NULL,
    aggregate_id   VARCHAR(255) NOT NULL,
    event_type     VARCHAR(255) NOT NULL,
    payload        JSONB,
    created_at     TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_outbox PRIMARY KEY (id)
);

-- changeset PhamDuyHuy:1751994419139-3
CREATE TABLE outbox_events
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_by     VARCHAR(255),
    updated_at     TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_by     VARCHAR(255),
    is_deleted     BOOLEAN                                 NOT NULL,
    deleted_at     TIMESTAMP WITHOUT TIME ZONE,
    deleted_by     VARCHAR(255),
    event_id       VARCHAR(255)                            NOT NULL,
    event_type     VARCHAR(255)                            NOT NULL,
    aggregate_id   VARCHAR(255)                            NOT NULL,
    aggregate_type VARCHAR(255)                            NOT NULL,
    payload        TEXT                                    NOT NULL,
    processed      BOOLEAN                                 NOT NULL,
    processed_at   TIMESTAMP WITHOUT TIME ZONE,
    retry_count    INTEGER                                 NOT NULL,
    max_retries    INTEGER                                 NOT NULL,
    next_retry_at  TIMESTAMP WITHOUT TIME ZONE,
    error_message  TEXT,
    CONSTRAINT pk_outbox_events PRIMARY KEY (id)
);

-- changeset PhamDuyHuy:1751994419139-6
ALTER TABLE outbox_events
    ADD CONSTRAINT uc_outbox_events_event UNIQUE (event_id);

