apiVersion: apps/v1
kind: Deployment
metadata:
  name: backoffice-bff
  labels:
    app: backoffice-bff
    type: bff
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backoffice-bff
  template:
    metadata:
      labels:
        app: backoffice-bff
    spec:
      containers:
      - name: backoffice-bff
        image: phamduyhuyuit/bookingsmart-backoffice-bff:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: backoffice-bff-service
spec:
  selector:
    app: backoffice-bff
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP
