apiVersion: apps/v1
kind: Deployment
metadata:
  name: storefront-fe
  labels:
    app: storefront-fe
    type: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storefront-fe
  template:
    metadata:
      labels:
        app: storefront-fe
    spec:
      containers:
      - name: storefront-fe
        image: phamduyhuyuit/bookingsmart-storefront-fe:latest
        ports:
        - containerPort: 3000
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: storefront-fe-service
spec:
  selector:
    app: storefront-fe
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: ClusterIP
