-- liquibase formatted sql

-- changeset PhamDuyHuy:1751788218928-1
CREATE TABLE airlines
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name      VARCHAR(100)                            NOT NULL,
    iata_code VARCHAR(2)                              NOT NULL,
    logo_url  VARCHAR(255),
    CONSTRAINT pk_airlines PRIMARY KEY (id)
);

-- changeset PhamDuyHuy:1751788218928-2
CREATE TABLE airports
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name      VARCHAR(100)                            NOT NULL,
    iata_code VARCHAR(3)                              NOT NULL,
    city      VARCHAR(100)                            NOT NULL,
    country   VARCHAR(100)                            NOT NULL,
    CONSTRAINT pk_airports PRIMARY KEY (id)
);

-- changeset PhamDuyHuy:1751788218928-3
CREATE TABLE flight_fares
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    flight_id  BIGINT                                  NOT NULL,
    fare_class VARCHAR(255)                            NOT NULL,
    price      DECIMAL(10, 2)                          NOT NULL,
    conditions TEXT,
    CONSTRAINT pk_flight_fares PRIMARY KEY (id)
);

-- changeset PhamDuyHuy:1751788218928-4
CREATE TABLE flight_inventory
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    flight_leg_id  BIGINT                                  NOT NULL,
    fare_class     VARCHAR(255)                            NOT NULL,
    total_seats    SMALLINT                                NOT NULL,
    reserved_seats SMALLINT                                NOT NULL,
    CONSTRAINT pk_flight_inventory PRIMARY KEY (id)
);

-- changeset PhamDuyHuy:1751788218928-5
CREATE TABLE flight_legs
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    flight_id            BIGINT                                  NOT NULL,
    leg_number           SMALLINT                                NOT NULL,
    departure_airport_id BIGINT                                  NOT NULL,
    arrival_airport_id   BIGINT                                  NOT NULL,
    departure_time       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    arrival_time         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_flight_legs PRIMARY KEY (id)
);

-- changeset PhamDuyHuy:1751788218928-6
CREATE TABLE flights
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_on       TIMESTAMP WITHOUT TIME ZONE,
    created_by       VARCHAR(255),
    last_modified_on TIMESTAMP WITHOUT TIME ZONE,
    last_modified_by VARCHAR(255),
    deleted          BOOLEAN                                 NOT NULL,
    is_active        BOOLEAN                                 NOT NULL,
    flight_number    VARCHAR(10)                             NOT NULL,
    airline_id       BIGINT                                  NOT NULL,
    aircraft_type    VARCHAR(50),
    CONSTRAINT pk_flights PRIMARY KEY (id)
);

-- changeset PhamDuyHuy:1751788218928-7
ALTER TABLE flight_fares
    ADD CONSTRAINT uc_088f717f7f3c991267726e216 UNIQUE (flight_id, fare_class);

-- changeset PhamDuyHuy:1751788218928-8
ALTER TABLE flight_inventory
    ADD CONSTRAINT uc_71fa7a57019dd0aebf1ee54e9 UNIQUE (flight_leg_id, fare_class);

-- changeset PhamDuyHuy:1751788218928-9
ALTER TABLE airlines
    ADD CONSTRAINT uc_airlines_iata_code UNIQUE (iata_code);

-- changeset PhamDuyHuy:1751788218928-10
ALTER TABLE airports
    ADD CONSTRAINT uc_airports_iata_code UNIQUE (iata_code);

-- changeset PhamDuyHuy:1751788218928-11
ALTER TABLE flight_legs
    ADD CONSTRAINT uc_b6b1fbef6a817bc10ec30aeb1 UNIQUE (flight_id, leg_number);

-- changeset PhamDuyHuy:1751788218928-12
ALTER TABLE flights
    ADD CONSTRAINT FK_FLIGHTS_ON_AIRLINE FOREIGN KEY (airline_id) REFERENCES airlines (id);

-- changeset PhamDuyHuy:1751788218928-13
ALTER TABLE flight_fares
    ADD CONSTRAINT FK_FLIGHT_FARES_ON_FLIGHT FOREIGN KEY (flight_id) REFERENCES flights (id);

-- changeset PhamDuyHuy:1751788218928-14
ALTER TABLE flight_inventory
    ADD CONSTRAINT FK_FLIGHT_INVENTORY_ON_FLIGHT_LEG FOREIGN KEY (flight_leg_id) REFERENCES flight_legs (id);

-- changeset PhamDuyHuy:1751788218928-15
ALTER TABLE flight_legs
    ADD CONSTRAINT FK_FLIGHT_LEGS_ON_ARRIVAL_AIRPORT FOREIGN KEY (arrival_airport_id) REFERENCES airports (id);

-- changeset PhamDuyHuy:1751788218928-16
ALTER TABLE flight_legs
    ADD CONSTRAINT FK_FLIGHT_LEGS_ON_DEPARTURE_AIRPORT FOREIGN KEY (departure_airport_id) REFERENCES airports (id);

-- changeset PhamDuyHuy:1751788218928-17
ALTER TABLE flight_legs
    ADD CONSTRAINT FK_FLIGHT_LEGS_ON_FLIGHT FOREIGN KEY (flight_id) REFERENCES flights (id);

