-- liquibase formatted sql

-- changeset PhamDuyHuy:1757504990159-2
CREATE TABLE aircraft
(
    aircraft_id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at          TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by          VARCHAR(255),
    updated_at          TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_by          VARCHAR(255),
    is_deleted          BOOLEAN                                 NOT NULL,
    deleted_at          TIMESTAMP WITHOUT TIME ZONE,
    deleted_by          VARCHAR(255),
    model               VARCHAR(100)                            NOT NULL,
    manufacturer        VARCHAR(100),
    capacity_economy    INTEGER,
    capacity_business   INTEGER,
    capacity_first      INTEGER,
    total_capacity      INTEGER,
    registration_number VARCHAR(20),
    is_active           BOOLEAN                                 NOT NULL,
    featured_media_id   BIGINT,
    CONSTRAINT pk_aircraft PRIMARY KEY (aircraft_id)
);

-- changeset PhamDuyHuy:1757504990159-3
ALTER TABLE flights
    ADD aircraft_id BIGINT;

-- changeset PhamDuyHuy:1757504990159-8
ALTER TABLE aircraft
    ADD CONSTRAINT uc_aircraft_registration_number UNIQUE (registration_number);

-- changeset PhamDuyHuy:1757504990159-9
ALTER TABLE flights
    ADD CONSTRAINT FK_FLIGHTS_ON_AIRCRAFT FOREIGN KEY (aircraft_id) REFERENCES aircraft (aircraft_id);


