-- liquibase formatted sql

-- changeset PhamDuyHuy:1756851889604-1
CREATE TABLE airline_images
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    airline_id    BIGINT                                  NOT NULL,
    image_url     VARCHAR(255)                            NOT NULL,
    image_type    VARCHAR(255),
    alt_text      VARCHAR(255),
    display_order INTEGER,
    is_primary    BOOLEAN,
    is_active     BOOLEAN,
    CONSTRAINT pk_airline_images PRIMARY KEY (id)
);

-- changeset PhamDuyHuy:1756851889604-2
CREATE TABLE airport_images
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    airport_id    BIGINT                                  NOT NULL,
    image_url     VARCHAR(255)                            NOT NULL,
    image_type    VARCHAR(255),
    alt_text      VARCHAR(255),
    display_order INTEGER,
    is_primary    BOOLEAN,
    is_active     BOOLEAN,
    CONSTRAINT pk_airport_images PRIMARY KEY (id)
);

-- changeset PhamDuyHuy:1756851889604-3
CREATE TABLE flight_images
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    flight_id     BIGINT                                  NOT NULL,
    image_url     VARCHAR(255)                            NOT NULL,
    image_type    VARCHAR(255),
    alt_text      VARCHAR(255),
    display_order INTEGER,
    is_primary    BOOLEAN,
    is_active     BOOLEAN,
    CONSTRAINT pk_flight_images PRIMARY KEY (id)
);

-- changeset PhamDuyHuy:1756851889604-4
ALTER TABLE airline_images
    ADD CONSTRAINT FK_AIRLINE_IMAGES_ON_AIRLINE FOREIGN KEY (airline_id) REFERENCES airlines (airline_id);

-- changeset PhamDuyHuy:1756851889604-5
ALTER TABLE airport_images
    ADD CONSTRAINT FK_AIRPORT_IMAGES_ON_AIRPORT FOREIGN KEY (airport_id) REFERENCES airports (airport_id);

-- changeset PhamDuyHuy:1756851889604-6
ALTER TABLE flight_images
    ADD CONSTRAINT FK_FLIGHT_IMAGES_ON_FLIGHT FOREIGN KEY (flight_id) REFERENCES flights (flight_id);

