spring:
  application:
    name: media-service
#   datasource:
#     url: jdbc:postgresql://localhost:5432/bookingsmart
#     username: postgres
#     password: password
#     driver-class-name: org.postgresql.Driver
#   jpa:
#     hibernate:
#       ddl-auto: validate
#     show-sql: false
#     database-platform: org.hibernate.dialect.PostgreSQLDialect
#     properties:
#       hibernate:
#         format_sql: true
#         jdbc:
#           time_zone: UTC

server:
  port: 8089
  servlet:
    context-path: /media

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.pdh.media: DEBUG
    org.springframework.web: DEBUG
