server:
  port: 8082
  servlet:
    context-path: /hotels
    
# OpenAPI Documentation Configuration
springdoc:
  api-docs:
    path: /api/docs
    enabled: true
  swagger-ui:
    path: /api/swagger-ui
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
    try-it-out-enabled: true
    oauth:
      clientId: swagger-ui
      realm: BookingSmart
      appName: ${spring.application.name}
  show-actuator: true
  group-configs:
    - group: 'public'
      display-name: 'Public API'
      paths-to-match: '/storefront/**'
    - group: 'admin'
      display-name: 'Admin API'
      paths-to-match: '/backoffice/**'
    - group: 'internal'
      display-name: 'Internal API'
      paths-to-match: ['/reserve', '/cancel-reservation', '/confirm-reservation']
    - group: 'monitoring'
      display-name: 'Monitoring & Health'
      paths-to-match: '**/health'

# API Documentation Properties
api:
  info:
    title: Hotel Service API
    description: Hotel management and booking API for the BookingSmart platform
    version: '@project.version@'
    contact:
      name: BookingSmart Hotel Team
      email: hotel-team@bookingsmart.com
    license:
      name: MIT License
      url: https://opensource.org/licenses/MIT
    oauth2:
      authorization-url: http://localhost:8080/realms/BookingSmart/protocol/openid-connect/auth
      token-url: http://localhost:8080/realms/BookingSmart/protocol/openid-connect/token
      refresh-url: http://localhost:8080/realms/BookingSmart/protocol/openid-connect/token
      scopes:
        admin: Administrative access to hotel management
        customer: Customer access to hotel search and booking
        partner: Partner access to hotel integration endpoints


spring:
  application:
    name: HOTEL-SERVICE
  profiles:
    active: local
  threads:
    virtual:
      enabled: true

---

spring:
  config:
    activate:
      on-profile: local
  devtools:
    restart:
      enabled: true
      poll-interval: 2000
      quiet-period: 1000
    livereload:
      enabled: true
      port: 35730
  datasource:
    url: jdbc:postgresql://localhost:5432/hotel_db
    username: postgres
    password: p0stgr3s
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
        temp:
          use_jdbc_metadata_defaults: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/BookingSmart
  ai:
    mcp:
      server:
        enabled: true
        stdio: false
        name: hotel-mcp-server
        version: 1.0.0
        type: sync
        base-url: /hotels
        capabilities:
          prompt: false
          completion: false
          resource: false
          tool: true

  liquibase:
    enabled: true
    default-schema: public
    change-log: classpath:db/changelog/db.changelog-master.yaml
  
  # Kafka Configuration - Optimized for local development
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: hotel-service-local
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      session-timeout-ms: 30000
      heartbeat-interval-ms: 10000
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: 1
      retries: 3
      batch-size: 16384
      linger-ms: 5

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    initial-instance-info-replication-interval-seconds: 5
    instance-info-replication-interval-seconds: 5
  instance:
    hostname: localhost
    prefer-ip-address: false
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
---

spring:
  config:
    activate:
      on-profile: docker
  ai:
    mcp:
      server:
        enabled: true
        stdio: false
        name: hotel-mcp-server
        version: 1.0.0
        type: sync
        base-url: /hotels
        capabilities:
          prompt: false
          completion: false
          resource: false
          tool: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI}
  liquibase:
    enabled: true
    default-schema: public
    change-log: classpath:db/changelog/db.changelog-master.yaml
  
  # Kafka Configuration - Minimal, inherit từ BaseKafkaConfig
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: hotel-service
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://discovery-service:8761/eureka}
    fetch-registry: true
    register-with-eureka: true
    initial-instance-info-replication-interval-seconds: 5
    instance-info-replication-interval-seconds: 5
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    io.modelcontextprotocol: DEBUG
    org.springframework.ai: DEBUG
    com.pdh.hotel: DEBUG
    org.hibernate.SQL: DEBUG
