-- liquibase formatted sql

-- changeset PhamDuyHuy:1752646988238-1
CREATE TABLE booking_outbox_events
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_id       VARCHAR(36)                             NOT NULL,
    event_type     VARCHAR(100)                            NOT NULL,
    aggregate_id   VARCHAR(100)                            NOT NULL,
    aggregate_type VARCHAR(50)                             NOT NULL,
    payload        JSONB                                   NOT NULL,
    processed      BOOLEAN                                 NOT NULL,
    processed_at   TIMESTAMP WITHOUT TIME ZONE,
    retry_count    INTEGER                                 NOT NULL,
    max_retries    INTEGER                                 NOT NULL,
    next_retry_at  TIMESTAMP WITHOUT TIME ZONE,
    error_message  TEXT,
    created_at     TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_by     VARCHAR(255),
    updated_at     TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_by     VARCHAR(255),
    is_deleted     BOOLEAN                                 NOT NULL,
    deleted_at     TIMESTAMP WITHOUT TIME ZONE,
    deleted_by     VARCHAR(255),
    CONSTRAINT pk_booking_outbox_events PRIMARY KEY (id)
);

-- changeset PhamDuyHuy:1752646988238-2
ALTER TABLE booking_outbox_events
    ADD CONSTRAINT uc_booking_outbox_events_event UNIQUE (event_id);

-- changeset PhamDuyHuy:1752646988238-3
CREATE INDEX idx_booking_outbox_aggregate ON booking_outbox_events (aggregate_type, aggregate_id);

-- changeset PhamDuyHuy:1752646988238-4
CREATE INDEX idx_booking_outbox_created_at ON booking_outbox_events (created_at);

-- changeset PhamDuyHuy:1752646988238-5
CREATE INDEX idx_booking_outbox_event_type ON booking_outbox_events (event_type);

-- changeset PhamDuyHuy:1752646988238-6
CREATE INDEX idx_booking_outbox_processed ON booking_outbox_events (processed);

-- changeset PhamDuyHuy:1752646988238-7
CREATE INDEX idx_booking_outbox_retry ON booking_outbox_events (processed, retry_count, next_retry_at);

-- changeset PhamDuyHuy:1752646988238-9
DROP TABLE outbox_events CASCADE;

