-- liquibase formatted sql

-- changeset PhamDuyHuy:1752055579892-1
CREATE TABLE booking_items
(
    item_id              UUID           NOT NULL,
    created_at           TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_by           VARCHAR(255),
    updated_at           TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_by           VARCHAR(255),
    is_deleted           BOOLEAN        NOT NULL,
    deleted_at           TIMESTAMP WITHOUT TIME ZONE,
    deleted_by           VARCHAR(255),
    booking_id           UUID           NOT NULL,
    service_type         VARCHAR(255)   NOT NULL,
    provider_booking_ref VARCHAR(255),
    status               VARCHAR(50),
    price                DECIMAL(12, 2) NOT NULL,
    details              JSONB,
    CONSTRAINT pk_booking_items PRIMARY KEY (item_id)
);

-- changeset PhamDuyHuy:1752055579892-2
CREATE TABLE booking_passengers
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at           TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_by           VARCHAR(255),
    updated_at           TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_by           VARCHAR(255),
    is_deleted           BOOLEAN                                 NOT NULL,
    deleted_at           TIMESTAMP WITHOUT TIME ZONE,
    deleted_by           VARCHAR(255),
    booking_id           UUID                                    NOT NULL,
    passenger_type       VARCHAR(255),
    title                VARCHAR(255),
    first_name           VARCHAR(255)                            NOT NULL,
    last_name            VARCHAR(255)                            NOT NULL,
    date_of_birth        date,
    nationality          VARCHAR(255),
    passport_number      VARCHAR(255),
    passport_expiry      date,
    seat_preference      VARCHAR(255),
    meal_preference      VARCHAR(255),
    special_assistance   VARCHAR(255),
    is_primary_passenger BOOLEAN,
    display_order        INTEGER,
    CONSTRAINT pk_booking_passengers PRIMARY KEY (id)
);

-- changeset PhamDuyHuy:1752055579892-3
CREATE TABLE booking_saga_instances
(
    saga_id             VARCHAR(255) NOT NULL,
    booking_id          UUID         NOT NULL,
    current_state       VARCHAR(255),
    started_at          TIMESTAMP WITHOUT TIME ZONE,
    last_updated_at     TIMESTAMP WITHOUT TIME ZONE,
    completed_at        TIMESTAMP WITHOUT TIME ZONE,
    is_compensating     BOOLEAN,
    compensation_reason VARCHAR(255),
    step_context        TEXT,
    version             BIGINT,
    CONSTRAINT pk_booking_saga_instances PRIMARY KEY (saga_id)
);

-- changeset PhamDuyHuy:1752055579892-4
CREATE TABLE booking_services
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at          TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_by          VARCHAR(255),
    updated_at          TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_by          VARCHAR(255),
    is_deleted          BOOLEAN                                 NOT NULL,
    deleted_at          TIMESTAMP WITHOUT TIME ZONE,
    deleted_by          VARCHAR(255),
    booking_id          UUID                                    NOT NULL,
    service_type        VARCHAR(255)                            NOT NULL,
    service_name        VARCHAR(255)                            NOT NULL,
    service_description VARCHAR(255),
    quantity            INTEGER,
    unit_price          DECIMAL(10, 2),
    total_price         DECIMAL(10, 2),
    currency            VARCHAR(255),
    is_mandatory        BOOLEAN,
    is_active           BOOLEAN,
    display_order       INTEGER,
    CONSTRAINT pk_booking_services PRIMARY KEY (id)
);

-- changeset PhamDuyHuy:1752055579892-5
CREATE TABLE bookings
(
    booking_id          UUID           NOT NULL,
    created_at          TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_by          VARCHAR(255),
    updated_at          TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_by          VARCHAR(255),
    is_deleted          BOOLEAN        NOT NULL,
    deleted_at          TIMESTAMP WITHOUT TIME ZONE,
    deleted_by          VARCHAR(255),
    booking_reference   VARCHAR(20)    NOT NULL,
    user_id             UUID           NOT NULL,
    total_amount        DECIMAL(12, 2) NOT NULL,
    currency            VARCHAR(3)     NOT NULL,
    status              VARCHAR(255)   NOT NULL,
    booking_type        VARCHAR(255)   NOT NULL,
    saga_state          VARCHAR(255)   NOT NULL,
    saga_id             VARCHAR(255)   NOT NULL,
    confirmation_number VARCHAR(50),
    cancelled_at        TIMESTAMP WITHOUT TIME ZONE,
    cancellation_reason VARCHAR(255),
    compensation_reason TEXT,
    CONSTRAINT pk_bookings PRIMARY KEY (booking_id)
);

-- changeset PhamDuyHuy:1752055579892-6
CREATE TABLE outbox_events
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_by     VARCHAR(255),
    updated_at     TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_by     VARCHAR(255),
    is_deleted     BOOLEAN                                 NOT NULL,
    deleted_at     TIMESTAMP WITHOUT TIME ZONE,
    deleted_by     VARCHAR(255),
    event_id       VARCHAR(255)                            NOT NULL,
    event_type     VARCHAR(255)                            NOT NULL,
    aggregate_id   VARCHAR(255)                            NOT NULL,
    aggregate_type VARCHAR(255)                            NOT NULL,
    payload        TEXT                                    NOT NULL,
    processed      BOOLEAN                                 NOT NULL,
    processed_at   TIMESTAMP WITHOUT TIME ZONE,
    retry_count    INTEGER                                 NOT NULL,
    max_retries    INTEGER                                 NOT NULL,
    next_retry_at  TIMESTAMP WITHOUT TIME ZONE,
    error_message  TEXT,
    CONSTRAINT pk_outbox_events PRIMARY KEY (id)
);

-- changeset PhamDuyHuy:1752055579892-7
CREATE TABLE saga_state_log
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at        TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_by        VARCHAR(255),
    updated_at        TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_by        VARCHAR(255),
    is_deleted        BOOLEAN                                 NOT NULL,
    deleted_at        TIMESTAMP WITHOUT TIME ZONE,
    deleted_by        VARCHAR(255),
    saga_id           VARCHAR(255)                            NOT NULL,
    booking_id        VARCHAR(255)                            NOT NULL,
    from_state        VARCHAR(255),
    to_state          VARCHAR(255)                            NOT NULL,
    event_type        VARCHAR(255)                            NOT NULL,
    event_payload     TEXT,
    compensation_data TEXT,
    error_message     TEXT,
    processed_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_saga_state_log PRIMARY KEY (id)
);

-- changeset PhamDuyHuy:1752055579892-8
ALTER TABLE booking_saga_instances
    ADD CONSTRAINT uc_booking_saga_instances_bookingid UNIQUE (booking_id);

-- changeset PhamDuyHuy:1752055579892-9
ALTER TABLE bookings
    ADD CONSTRAINT uc_bookings_booking_reference UNIQUE (booking_reference);

-- changeset PhamDuyHuy:1752055579892-10
ALTER TABLE outbox_events
    ADD CONSTRAINT uc_outbox_events_event UNIQUE (event_id);

-- changeset PhamDuyHuy:1752055579892-11
ALTER TABLE booking_items
    ADD CONSTRAINT FK_BOOKING_ITEMS_ON_BOOKING FOREIGN KEY (booking_id) REFERENCES bookings (booking_id);

-- changeset PhamDuyHuy:1752055579892-12
ALTER TABLE booking_passengers
    ADD CONSTRAINT FK_BOOKING_PASSENGERS_ON_BOOKING FOREIGN KEY (booking_id) REFERENCES bookings (booking_id);

-- changeset PhamDuyHuy:1752055579892-13
ALTER TABLE booking_services
    ADD CONSTRAINT FK_BOOKING_SERVICES_ON_BOOKING FOREIGN KEY (booking_id) REFERENCES bookings (booking_id);

