-- liquibase formatted sql

-- changeset PhamDuyHuy:1757207654533-1
CREATE TABLE media
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by        VARCHAR(255),
    updated_at        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_by        VARCHAR(255),
    is_deleted        BOOLEAN                                 NOT NULL,
    deleted_at        TIMESTAMP WITHOUT TIME ZONE,
    deleted_by        VARCHAR(255),
    public_id         VARCHAR(255)                            NOT NULL,
    url               VARCHAR(500)                            NOT NULL,
    secure_url        VARCHAR(500)                            NOT NULL,
    entity_type       VARCHAR(50)                             NOT NULL,
    entity_id         BIGINT                                  NOT NULL,
    media_type        VARCHAR(50)                             NOT NULL,
    resource_type     VARCHAR(20),
    format            VARCHAR(10),
    original_filename VARCHAR(255),
    folder            VARCHAR(255),
    file_size         BIGINT,
    width             INTEGER,
    height            INTEGER,
    alt_text          VARCHAR(255),
    display_order     INTEGER,
    is_primary        BOOLEAN                                 NOT NULL,
    is_active         BOOLEAN                                 NOT NULL,
    metadata          TEXT,
    tags              VARCHAR(500),
    version           BIGINT,
    asset_id          VARCHAR(255),
    CONSTRAINT pk_media PRIMARY KEY (id)
);

-- changeset PhamDuyHuy:1757207654533-2
ALTER TABLE media
    ADD CONSTRAINT uc_media_public UNIQUE (public_id);

-- changeset PhamDuyHuy:1757207654533-3
CREATE INDEX idx_media_active ON media (is_active);

-- changeset PhamDuyHuy:1757207654533-4
CREATE INDEX idx_media_display_order ON media (entity_type, entity_id, display_order);

-- changeset PhamDuyHuy:1757207654533-5
CREATE INDEX idx_media_entity ON media (entity_type, entity_id);

-- changeset PhamDuyHuy:1757207654533-6
CREATE INDEX idx_media_primary ON media (entity_type, entity_id, is_primary);

-- changeset PhamDuyHuy:1757207654533-7
CREATE UNIQUE INDEX idx_media_public_id ON media (public_id);

-- changeset PhamDuyHuy:1757207654533-8
CREATE INDEX idx_media_type ON media (entity_type, entity_id, media_type);



